---
title: "National situation - Charts"
author: "Marcelo Eduardo Redoschi"
output: html_document
---

```{r echo=FALSE, message=FALSE}
library(readr)
library(lubridate)
library(dplyr)
library(markdown)
library(ggplot2)
source("helper_functions.R")
datasets_path<-file.path(getwd(),"..", "Protezione-Civile-Dataset","COVID-19") 
```

*Source: dpc-covid19-ita-andamento-nazionale.csv, own calculations*

```{r echo=FALSE, message=FALSE}
national_csv_fname<-file.path(datasets_path,"dati-andamento-nazionale","dpc-covid19-ita-andamento-nazionale.csv")
national<-read.csv(national_csv_fname,encoding="UTF-8", na.strings="undefined") 
```

```{r echo=FALSE, message=FALSE}
national$dt<-as.Date(ymd_hms(national$data))
national$data<-NULL 
national$stato<-NULL
col_names<-colnames(national)

intl_col_names<-gsub("ricoverati_con_sintomi","hospitalized_with_symptoms",col_names)
intl_col_names<-gsub("terapia_intensiva","intensive_care",intl_col_names)
intl_col_names<-gsub("totale_ospedalizzati","hospitalized_total",intl_col_names)
intl_col_names<-gsub("isolamento_domiciliare","home_isolation",intl_col_names)
intl_col_names<-gsub("variazione_totale_positivi","num_positives_variation",intl_col_names)
intl_col_names<-gsub("totale_positivi","positives_remaining",intl_col_names)
intl_col_names<-gsub("nuovi_positivi","positives_added_on_dt",intl_col_names)
intl_col_names<-gsub("dimessi_guariti","total_discharged_healed",intl_col_names)
intl_col_names<-gsub("deceduti","total_deceased",intl_col_names)
intl_col_names<-gsub("totale_casi","total_cases",intl_col_names)
intl_col_names<-gsub("tamponi","tests",intl_col_names)
intl_col_names<-gsub("note_","notes_",intl_col_names)
colnames(national)<-intl_col_names
national<-arrange(national, dt)
```

```{r echo=FALSE, message=FALSE}
nat<-national[-1,]
nat$dt_previous<-ymd(nat$dt)-1
nat2<-national[-(nrow(national)),]
nat2$notes_it<-NULL 
nat2$notes_en<-NULL 
col_names_previous_dt<-paste(colnames(nat2),'previous',sep="_")
colnames(nat2)<-col_names_previous_dt
nat3<-full_join(nat, nat2, by='dt_previous')
nat3<-arrange(nat3, dt)
nat3$tests_delta<-nat3$tests-nat3$tests_previous
nat3$home_isolation_delta<-nat3$home_isolation-nat3$home_isolation_previous
nat3$hospitalized_with_symptoms_delta<-nat3$hospitalized_with_symptoms-nat3$hospitalized_with_symptoms_previous
nat3$intensive_care_delta<-nat3$intensive_care-nat3$intensive_care_previous
nat3$discharged_healed_delta<-nat3$total_discharged_healed-nat3$total_discharged_healed_previous
nat3$deceased_delta<-nat3$total_deceased-nat3$total_deceased_previous
nat3$positives_remaining_delta<-nat3$positives_remaining-nat3$positives_remaining_previous
#identical(nat3$positives_remaining_delta, nat3$num_positives_variation)
```
```{r echo=FALSE, message=FALSE}
nat3$total_tests_cases_ratio_prev<-nat3$tests_prev/nat3$total_cases_previous
nat3$tests_per_positive_on_dt_ratio<-nat3$tests_delta/nat3$positives_added_on_dt
nat3$positives_remaining_percent_delta<-nat3$positives_remaining_delta/nat3$positives_remaining_previous*100
nat3$deceased_per_positives_day_before_ratio<-nat3$deceased_delta/nat3$positives_remaining_previous*100
nat3$discharged_healed_per_positives_day_before_ratio<-nat3$discharged_healed_delta/nat3$positives_remaining_previous*100
```

```{r echo=FALSE}
      nat_fatalities<-select(national,total_deceased, total_cases, positives_added_on_dt, dt)
      nat_fatalities$rate<-nat_fatalities$total_deceased/nat_fatalities$total_cases*100
    nat_fatalities<-select(nat_fatalities,total_deceased, total_cases, rate, dt, positives_added_on_dt)
```

```{r fig.height=5, fig.width=10, echo=FALSE}
      chart1_title<-paste('Total cases',format(min(national$dt),"%d %b"),"-",format(max(national$dt),"%d %b %Y"))
    
    chart1<-ggplot(national, aes(y=log10(total_cases), x=dt))+geom_line(color="#40B35A", linetype=2)+ggtitle(chart1_title)+ylab("Logarithmic scale")+xlab("Date")
    
    print(chart1)
```
```{r fig.height=5, fig.width=10, echo=FALSE}
      chart2_title<-paste('Total fatalities',format(min(national$dt),"%d %b"),"-",format(max(national$dt),"%d %b %Y"))
    
    chart2<-ggplot(nat_fatalities, aes(y=log10(total_deceased), x=dt))+geom_line(color="#98234a")+ggtitle(chart2_title)+ylab("Logarithmic scale")+xlab("Date")
    
    print(chart2)

    print(nat_fatalities)

```
```{r fig.height=5, fig.width=10, echo=FALSE, message=FALSE}


    chart3_title<-paste('Remaining active cases (daily change)',format(min(national$dt),"%d %b"),"-",format(max(national$dt),"%d %b %Y"))
    
    chart3<-ggplot(nat3, aes(y=deceased_per_positives_day_before_ratio, x=dt))+geom_path(color="orange")+ggtitle(chart3_title)+xlab("Date")+
 ylab("In thousands")
    print(chart3)

```

```{r echo=FALSE, message=FALSE}
nat4<-select(nat3, dt, positives_remaining_previous, deceased_delta, discharged_healed_delta, deceased_per_positives_day_before_ratio, discharged_healed_per_positives_day_before_ratio)
nat4$discharged_or_healed_to_deceased_ratio<-nat4$discharged_healed_per_positives_day_before_ratio/nat4$deceased_per_positives_day_before_ratio
```

```{r fig.height=5, fig.width=10, echo=FALSE, message=FALSE}

    chart4_title<-paste('Fatalities per active cases on the previous day',format(min(national$dt)+1,"%d %b"),"-",format(max(national$dt),"%d %b %Y"))
    
    chart4<-ggplot(nat4, aes(y=deceased_per_positives_day_before_ratio, x=dt))+geom_line(color="red",linetype=2)+ggtitle(chart4_title)+xlab(paste(format(min(nat$dt),"%d %b"),"-",format(max(nat$dt),"%d %b %Y")))+
 ylab("%")
    print(chart4)

```

```{r fig.height=5, fig.width=10, echo=FALSE, message=FALSE}
    
    chart5_title<-paste('Discharged or healed per positive cases on the previous day',format(min(national$dt)+1,"%d %b"),"-",format(max(national$dt),"%d %b"))
    

    chart5<-ggplot(nat4, aes(y=discharged_healed_per_positives_day_before_ratio, x=dt))+geom_line(color="green")+ggtitle(chart5_title)+xlab("Date")+ylab("Proportion")
    print(chart5)
```


```{r fig.height=5, fig.width=10, echo=FALSE, message=FALSE}

    chart6_title<-paste('Active cases remaining the day before per each healed or discharged')
    
    chart6<-ggplot(nat4, aes(y=positives_remaining_previous/discharged_healed_delta, x=dt))+geom_line(color="purple",linetype=5)+ggtitle(chart6_title)+xlab(paste(format(min(national$dt)+1,"%d %b"),"-",format(max(national$dt),"%d %b %Y")))+ylab("Proportion (smaller numbers are better)")
    print(chart6)
```


```{r fig.height=5, fig.width=10, echo=FALSE, message=FALSE}
    
    chart7_title<-paste('Discharged or healed per fatality proportion',format(min(national$dt),"%d %b"),"-",format(max(national$dt),"%d %b %Y"))

    chart7<-ggplot(nat4, aes(y=discharged_healed_delta/deceased_delta, x=dt))+geom_line(color="#7D2860")+ggtitle(chart7_title)+xlab("Date")+ylab("Higher figures are better")
    print(chart7)
```



```{r echo=FALSE, message=FALSE}
#print(select(nat4, dt, discharged_or_healed_to_deceased_ratio))
#summary(nat4$discharged_or_healed_to_deceased_ratio)
```


```{r echo=FALSE, message=FALSE}
nat5<-select(nat3, dt, total_discharged_healed, total_deceased, positives_remaining, total_cases)
nat5$inactive_discharged_healed_deceased<-nat5$total_discharged_healed+nat5$total_deceased
nat5$active<-nat5$total_cases-nat5$inactive_discharged_healed_deceased
nat5$pos<-backlog_dt(nat5, nat5$inactive_discharged_healed_deceased)

nat6<-select(nat5,dt, inactive_discharged_healed_deceased, positives_remaining, total_cases)

nat6$trailing_dt<-nat6$dt 

for (i in 1:nrow(nat5) ) { 
	
	x<-nat5[i,]$inactive_discharged_healed_deceased
	y<-backlog_dt(nat5, x) 
#	print(paste(i, y))
	nat6$trailing_dt[i]<-y
	nat6$num_days_trailing<-nat6$dt-nat6$trailing_dt
}
```

```{r echo=FALSE, message=FALSE}
initial_num_cases<-min(nat6$total_cases)
national_case_backlog<-nat6[nat6$inactive_discharged_healed_deceased>=initial_num_cases,]
```

