---
title: "Situation by province - Charts"
author: "Marcelo Eduardo Redoschi"
output: html_document
---

```{r echo=FALSE, message=FALSE}
## 1. Initial setup 
### Libraries and paths 
library(readr)
library(lubridate)
library(dplyr)
library(markdown)
source("helper_functions.R")
datasets_path<-file.path(getwd(),"..", "COVID-19") 
```

*Own calculations, based on dpc-covid19-ita-province.csv*
```{r echo=FALSE, message=FALSE}
## 2. Provincial data - CSV Import step
provinces_csv_fname<-file.path(datasets_path,"dati-province","dpc-covid19-ita-province.csv")

# na.string explicitly set to something else, since NA in this file means the Naples province abbreviation!
provinces_raw<-read.csv(provinces_csv_fname,encoding="UTF-8", na.strings="undefined") 


```


```{r echo=FALSE, message=FALSE}
## 3. Filter out rows marked "In fase di definizione/aggiornamento"
to_be_determined_or_updated<-"In fase di definizione/aggiornamento"
provinces_it<-provinces_raw[provinces_raw$denominazione_provincia!=to_be_determined_or_updated,]
```

```{r echo=FALSE, message=FALSE}
## 4. Italian administrative regions
italian_adm_regions<-distinct(select(provinces_it, denominazione_regione, codice_regione))
col_names<-colnames(italian_adm_regions)
intl_col_names<-gsub("denominazione_regione","region_name",col_names)
intl_col_names2<-gsub("codice_regione","region_code",intl_col_names)
colnames(italian_adm_regions)<-intl_col_names2 
rm(intl_col_names)
rm(intl_col_names2)
italian_adm_regions<-arrange(italian_adm_regions, region_name)
```

```{r echo=FALSE, message=FALSE}
## 5. Italian provinces (belong to one region and contain more than one city or municipality)
italian_adm_provinces<-distinct(select(provinces_it, denominazione_provincia, codice_provincia, sigla_provincia, denominazione_regione, codice_regione, lat, long))
col_names<-colnames(italian_adm_provinces)
intl_col_names<-gsub("denominazione_provincia","province_name",col_names)
intl_col_names2<-gsub("codice_provincia","province_code",intl_col_names)
intl_col_names3<-gsub("sigla_provincia","province_abbreviation",intl_col_names2)
intl_col_names4<-gsub("denominazione_regione","region_name",intl_col_names3)
intl_col_names5<-gsub("codice_regione","region_code",intl_col_names4)

colnames(italian_adm_provinces)<-intl_col_names5 
rm(intl_col_names)
rm(intl_col_names2)
rm(intl_col_names3)
rm(intl_col_names4)
rm(intl_col_names5)
italian_adm_provinces<-arrange(italian_adm_provinces,  province_name)
# should have zero observations, if Naples was imported correctly.
# provinces_without_abbreviation<-italian_adm_provinces[is.na(italian_adm_provinces$province_abbreviation),] 
```


```{r echo=FALSE, message=FALSE}
## 6. Provinces case data
provinces<-select(provinces_it, data, codice_provincia, totale_casi)
provinces$dt<-as.Date(ymd_hms(provinces$data))
provinces$data<-NULL 
col_names<-colnames(provinces)
intl_col_names<-gsub("codice_provincia","province_code",col_names)
intl_col_names2<-gsub("totale_casi","total_cases",intl_col_names)
colnames(provinces)<-intl_col_names2
```

```{r echo=FALSE, message=FALSE}
most_recent_dt<-max(provinces$dt)
one_day_before<-most_recent_dt-1
two_days_before<-most_recent_dt-2
three_days_before<-most_recent_dt-3
```

```{r echo=FALSE, message=FALSE}
prov_most_recent_dt<-provinces[provinces$dt==most_recent_dt,]
prov_most_recent_dt$current_total<-prov_most_recent_dt$total_cases 
prov_most_recent_dt$total_cases<-NULL 
```

```{r echo=FALSE, message=FALSE}
prov_1_day_before<-provinces[provinces$dt==one_day_before,]
prov_1_day_before$dt<-NULL
prov_1_day_before$yesterday_total_cases<-prov_1_day_before$total_cases 
prov_1_day_before$total_cases<-NULL
```


```{r echo=FALSE, message=FALSE}
### Join
prov<-inner_join(prov_1_day_before, prov_most_recent_dt)
prov$todays_rate<-prov$current_total/prov_1_day_before$yesterday_total_cases
```


```{r echo=FALSE, message=FALSE}
### Two days prior
prov_2_days_before<-provinces[provinces$dt==two_days_before,]
prov_2_days_before$dt<-NULL
prov_2_days_before$total_two_days_before<-prov_2_days_before$cases
col_names<-colnames(prov_2_days_before)
revised_col_names<-gsub("total_cases","total_cases_two_days_before",col_names)
colnames(prov_2_days_before)<-revised_col_names
```

```{r echo=FALSE, message=FALSE}
### Three days prior
prov_3_days_before<-provinces[provinces$dt==three_days_before,]
prov_3_days_before$dt<-NULL
prov_3_days_before$total_two_days_before<-prov_3_days_before$cases
col_names<-colnames(prov_3_days_before)
revised_col_names<-gsub("total_cases","total_cases_three_days_before",col_names)
colnames(prov_3_days_before)<-revised_col_names
```

```{r echo=FALSE, message=FALSE}
provinces_calc<-inner_join(prov_most_recent_dt, prov_1_day_before)
provinces_calc<-inner_join(provinces_calc, prov_2_days_before)
provinces_calc<-inner_join(provinces_calc, prov_3_days_before)
provinces_calc$current_rate<-provinces_calc$current_total/provinces_calc$yesterday_total_cases
provinces_calc$yesterdays_rate<-provinces_calc$yesterday_total_cases/provinces_calc$total_cases_two_days_before
provinces_calc$rate_two_days_before<-provinces_calc$total_cases_two_days_before/provinces_calc$total_cases_three_days_before
province_names<-select(italian_adm_provinces, province_code, province_name, province_abbreviation)
provinces_calc<-inner_join(province_names, provinces_calc)
rm(province_names)
```


```{r echo=FALSE, message=FALSE}
#Cubic rate calculation 
provinces_calc$cubic_rate<-(provinces_calc$current_total/provinces_calc$total_cases_three_days_before)^(1/3)
provinces_calc$trend<-round((provinces_calc$current_rate-provinces_calc$cubic_rate)*100, digits=1)
```


```{r echo=FALSE, message=FALSE} 
write.csv(provinces_calc,"provinces_calc.csv")
```

### Graph - Total case progression - subnational level (last three days - cubic rate)

#### Provinces by Region 

```{r echo=FALSE, message=FALSE}
require(ggplot2)

for (i in 1:nrow(italian_adm_regions) ) {
	
    specified_region_name<-as.character(italian_adm_regions[i,]$region_name)

    regional_code<-italian_adm_regions[italian_adm_regions$region_name==specified_region_name,]$region_code
    
    local_provinces<-italian_adm_provinces[italian_adm_provinces$region_code==regional_code,]
  
    local_province_data<-inner_join(provinces_calc, local_provinces)
    local_province_data<-arrange(local_province_data, province_abbreviation)    

    local_province_data$cubic_percent_rate<-(local_province_data$cubic_rate-1)*100
    
    print(ggplot(local_province_data, aes(y=cubic_percent_rate, x=province_abbreviation))+ geom_boxplot(color='blue')+ ggtitle(specified_region_name)+ xlab("Province abbreviation") + ylab("cubic % rate"))
        
}
```


*To do: adjust import from original dataset, to place Trento and Bolzano provinces under the same administrative region.* 

**Data last updated: 7/Apr/2020**
