---
title: "Provinces supplemental - DRAFT"
author: "Marcelo Eduardo Redoschi"
output: html_document
---

```{r echo=FALSE, message=FALSE}
source(file.path(getwd(),"helper_functions.R"))
library(ggplot2)
unexpanded_columns<-grep("totale_casi_",colnames(provinces_data), invert=TRUE)
provinces_data_unexpanded<-provinces_data[,unexpanded_columns]
total_cases_by_province<-select(provinces_data_unexpanded, dt, denominazione_provincia, denominazione_regione, totale_casi)

total_cases_by_province<-translated_column_names(total_cases_by_province)

# sorted by region name
total_cases_by_province<-arrange(total_cases_by_province, denominazione_regione, province_name, total_cases)

selected_province_name<-"Roma"

individual_province_data<-total_cases_by_province[total_cases_by_province$province_name==selected_province_name,]

num_days_recorded<-nrow(individual_province_data)


individual_province_data$total_cases_day_before<-head_na(individual_province_data$total_cases,1)
#individual_province_data$total_cases_two_days_before<-head_na(individual_province_data$total_cases,2)
individual_province_data$total_cases_three_days_before<-head_na(individual_province_data$total_cases,3)

individual_province_data$current_rate<-(individual_province_data$total_cases)/(individual_province_data$total_cases_day_before)
individual_province_data$current_perc_rate<-(individual_province_data$current_rate-1)*100
individual_province_data$growth_factor_in_three_days<-((individual_province_data$total_cases)/(individual_province_data$total_cases_three_days_before))
individual_province_data$cubic_rate<-'^'(individual_province_data$growth_factor_in_three_days,1/3)
individual_province_data$cubic_perc_rate<-(individual_province_data$cubic_rate-1)*100
```

```{r echo=FALSE, message=FALSE}
individual_province_rates<-individual_province_data[is.finite(individual_province_data$cubic_perc_rate),]
  
  province_chart<-provincial_cubic_rate_chart(individual_province_rates,selected_province_name)
 
  print(province_chart)
```
```{r echo=FALSE, message=FALSE}
for (i in 1:nrow(italian_regions)) {
selected_region_name <- as.character(italian_regions[i, ])
txt<-"-------------------------------------------"
txt2<-"<><><><><><><><><><><><><><><><>"
print(paste(txt,selected_region_name,txt))

local_provinces_key<-provinces_regions_key[provinces_regions_key$denominazione_regione==selected_region_name,]
local_province_names<-local_provinces_key$province_name
print(local_province_names)
print(paste(txt2,txt2,txt2,sep=''))
} 
```

*This page last updated: 19/4/2020*
